version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dockernet

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dockernet

  prisma-user:
    image: node:20
    container_name: prisma-user-cli
    working_dir: /app
    volumes:
      - ./services/user-service:/app
    networks:
      - dockernet
    depends_on:
      - postgres
    entrypoint: ["sh", "-c", "npx prisma generate"]

  prisma-task:
    image: node:20
    container_name: prisma-task-cli
    working_dir: /app
    volumes:
      - ./services/task-service:/app
    networks:
      - dockernet
    depends_on:
      - postgres
    entrypoint: ["sh", "-c", "npx prisma generate"]

  prisma-category:
    image: node:20
    container_name: prisma-category-cli
    working_dir: /app
    volumes:
      - ./services/category-service:/app
    networks:
      - dockernet
    depends_on:
      - postgres
    entrypoint: ["sh", "-c", "npx prisma generate"]

volumes:
  pgdata:

networks:
  dockernet:
